# Generated by Django 5.2.6 on 2025-09-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NionsoDRF', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='unit_price',
        ),
    ]
