# Generated by Django 5.2.6 on 2025-09-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NionsoDRF', '0003_remove_cart_price_remove_cart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NionsoDRF.order'),
        ),
    ]
